development:
  environment: "sandbox"
  username: "signupforuseratsandboxpaypal"
  password: "signupforuseratsandboxpaypal"
  signature: "signupforuseratsandboxpaypal"
  application_id: "APP-TEST"

test:
  environment: "sandbox"
  username: "signupforuseratsandboxpaypal"
  password: "signupforuseratsandboxpaypal"
  signature: "signupforuseratsandboxpaypal"
  application_id: "APP-TEST"

production:
  environment: "production"
  username: "my_production_username"
  password: "my_production_password"
  signature: "my_production_signature"
  application_id: "my_production_app_id"